# This is a basic workflow to help you get started with Actions
name: CI
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build1:
    runs-on: self-hosted
    steps:
      - name: Run a one-line script1
        run: echo build1
  build2:
    runs-on: self-hosted
    steps:
      - name: Run a one-line script
        run: echo build2
  build3:
    runs-on: self-hosted
    steps:
      - name: Get Token
        id: get_new_token
        uses: peter-murray/workflow-application-token-action@v1
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
      - name: Create Issue
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ steps.get_new_token.outputs.token }}
          title: Test Issue
          body: |
            This is a test issue created using github actions.
  build4:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: python3 test.py
